version: '3.8'
services:
    ui:
        image: node:18-bookworm-slim
        command: sh -c "yarn install && yarn run dev"
        container_name: ui
        working_dir: /app
        env_file: .env
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./:/app
